name: time_picker_sheet_fork
description: "Time picker sheet library, allows you to have beauty time picker sheet with customable design to align with your requirements."
homepage: https://github.com/yoktavian/time-picker-sheet

version: 0.0.4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.yoktavian.time_picker_sheet
        pluginClass: TimePickerSheetPlugin
      ios:
        pluginClass: TimePicker